package com.example.ironlog

val exerciseList = listOf(
    Exercise("Dip", "Chest Pec Tricep"),
    Exercise("Bench Press", "Chest Pec"),
    Exercise("Squat", "Legs Quads Glutes"),
    Exercise("Deadlift", "Legs Back Hamstrings Glutes"),
    Exercise("Overhead Press", "Shoulder Delt Tricep"),
    Exercise("Barbell Row", "Back Lats"),
    Exercise("Incline Bench Press", "Chest Pec"),
    Exercise("Decline Bench Press", "Chest Pec"),
    Exercise("Dumbbell Chest Fly", "Chest Pec"),
    Exercise("Incline Cable Fly", "Chest Pec"),
    Exercise("Decline Cable Fly", "Chest Pec"),
    Exercise("Pull Up", "Back Lats"),
    Exercise("Chin Up", "Back Lats Bicep"),
    Exercise("Cable Chest Fly", "Chest Pec"),
    Exercise("Close-Grip Bench Press", "Tricep"),
    Exercise("Dumbbell Bench Press", "Chest Pec"),
    Exercise("Dumbbell Pullover", "Chest Pec"),
    Exercise("Larsen Press", "Chest Pec"),
    Exercise("Incline Dumbbell Press", "Chest Pec"),
    Exercise("Incline Push Up", "Chest Pec"),
    Exercise("Decline Push Up", "Chest Pec"),
    Exercise("Push Up", "Chest Pec"),
    Exercise("Machine Pec Fly", "Chest Pec"),
    Exercise("Machine Chest Press", "Chest Pec"),
    Exercise("Smith Machine Bench Press", "Chest Pec"),
    Exercise("Incline Smith Bench Press", "Chest Pec"),
    Exercise("Front Raise", "Shoulder Delt"),
    Exercise("Rear Delt Row", "Shoulder Delt"),
    Exercise("Upright Row", "Shoulder Delt"),
    Exercise("Cable Lateral Raise", "Shoulder Delt"),
    Exercise("Lateral Raise", "Shoulder Delt"),
    Exercise("Dumbbell Shoulder Press", "Shoulder Delt"),
    Exercise("Face Pull", "Shoulder Delt"),
    Exercise("Machine Lateral Raise", "Shoulder Delt"),
    Exercise("Machine Shoulder Press", "Shoulder Delt"),
    Exercise("Reverse Cable Fly", "Shoulder Delt"),
    Exercise("Reverse Dumbbell Fly", "Shoulder Delt"),
    Exercise("Reverse Machine Fly", "Shoulder Delt Back"),
    Exercise("Rear Delt Machine Fly", "Shoulder Delt Back"),
    Exercise("Squat Jerk", "Legs Quads"),
    Exercise("Split Jerk", "Shoulder Delt"),
    Exercise("Barbell Curl", "Bicep"),
    Exercise("Preacher Curl", "Bicep"),
    Exercise("Cable Curl", "Bicep"),
    Exercise("Concentration Curl", "Bicep"),
    Exercise("Dumbbell Curl", "Bicep"),
    Exercise("Hammer Curl", "Bicep"),
    Exercise("Incline Dumbbell Curl", "Bicep"),
    Exercise("Machine Bicep Curl", "Bicep"),
    Exercise("Spider Curl", "Bicep"),
    Exercise("Skullcrusher", "Tricep"),
    Exercise("Close-Grip Push Up", "Tricep"),
    Exercise("Dumbbell Triceps Extension", "Tricep"),
    Exercise("Overhead Triceps Extension", "Tricep"),
    Exercise("Tricep Pushdown", "Tricep"),
    Exercise("Dumbbell Kickbacks", "Tricep"),
    Exercise("Hack Squat", "Legs Quads"),
    Exercise("Barbell Lunge", "Legs Quads Glutes"),
    Exercise("Walking Lunge", "Legs Quads Glutes"),
    Exercise("Box Squat", "Legs Quads Glutes"),
    Exercise("Bulgarian Split Squat", "Legs Quads Glutes"),
    Exercise("Dumbbell Lunge", "Legs Quads Glutes"),
    Exercise("Front Squat", "Legs Quads Glutes"),
    Exercise("Arnold Press", "Shoulder Delt"),
    Exercise("Goblet Squat", "Legs Quads Glutes"),
    Exercise("Hip Adduction Machine", "Legs Glutes"),
    Exercise("Hip Abduction Machine", "Legs Glutes"),
    Exercise("Landmine Squat", "Legs Quads Glutes"),
    Exercise("Leg Extension", "Legs Quads"),
    Exercise("Leg Press", "Legs Quads Glutes"),
    Exercise("Lying Leg Curl", "Legs Hamstrings"),
    Exercise("Leg Curl", "Legs Hamstrings"),
    Exercise("Romanian Deadlift", "Legs Hamstrings"),
    Exercise("Side Lunge", "Legs Quads Glutes"),
    Exercise("Smith Machine Squat", "Legs Quads Glutes"),
    Exercise("Step Up", "Legs Quads Glutes"),
    Exercise("Back Extension", "Back"),
    Exercise("Barbell Shrug", "Back Traps"),
    Exercise("Cable Row", "Back Lats"),
    Exercise("Clean", "Legs Quads Glutes Shoulder Delt"),
    Exercise("Clean and Jerk", "Legs Quads Glutes Shoulder Delt"),
    Exercise("Dumbbell Row", "Back Lats"),
    Exercise("Dumbbell Shrug", "Back Traps"),
    Exercise("Good Morning", "Back Hamstrings"),
    Exercise("Hang Clean", "Legs Quads Glutes Shoulder Delt"),
    Exercise("Hang Snatch", "Legs Quads Glutes Shoulder Delt"),
    Exercise("Inverted Row", "Back Lats"),
    Exercise("Jefferson Curl", "Back Hamstrings"),
    Exercise("Lat Pulldown", "Back Lats"),
    Exercise("One-Handed Cable Row", "Back Lats"),
    Exercise("One-Handed Lat Pulldown", "Back Lats"),
    Exercise("Pendlay Row", "Back Lats"),
    Exercise("Power Clean", "Legs Quads Glutes Shoulder Delt"),
    Exercise("Power Snatch", "Legs Quads Glutes Shoulder Delt"),
    Exercise("Rack Pull", "Back Hamstrings"),
    Exercise("Seal Row", "Back Lats"),
    Exercise("Seated Machine Row", "Back Lats"),
    Exercise("Snatch", "Legs Quads Glutes Shoulder Delt"),
    Exercise("Stiff Leg Deadlift", "Back Hamstrings"),
    Exercise("T-Bar Row", "Back Lats"),
    Exercise("Trap Bar Deadlift", "Legs Back Hamstrings"),
    Exercise("Glute Bridge", "Legs Glutes"),
    Exercise("Hip Thrust", "Legs Hamstrings Glutes"),
    Exercise("Hip Thrust Machine", "Legs Hamstrings Glutes"),
    Exercise("Machine Glute Kickback", "Legs Glutes"),
    Exercise("One-Legged Hip Thrust", "Legs Hamstrings Glutes"),
    Exercise("One-Legged Leg Press", "Legs Quads Glutes"),
    Exercise("Cable Crunch", "Abs"),
    Exercise("Sit Up", "Abs"),
    Exercise("Lying Leg Raise", "Abs"),
    Exercise("Machine Crunch", "Abs"),
    Exercise("Ab Twist Machine", "Abs"),
    Exercise("Seated Calf Raise", "Legs Calves"),
    Exercise("Standing Calf Raise", "Legs Calves"),
    Exercise("Donkey Calf Raise", "Legs Calves"),
    Exercise("Wrist Curl", "Forearms"),
    Exercise("Wide-Grip Pull Up", "Back Lats"),
    Exercise("Wide-Grip Machine Row", "Back Lats"),
    Exercise("Wide-Grip Lat Pulldown", "Back Lats"),
    Exercise("Wide-Grip Cable Row", "Back Lats"),
)