package com.example.ironlog

//val oldExerciseLists = listOf(
//    OldExercise("Overhead Press", "Shoulder Delt Tricep"),
//    OldExercise("Barbell Row", "Back Lats"),
//    OldExercise("Incline Bench Press", "Chest Pec"),
//    OldExercise("Decline Bench Press", "Chest Pec"),
//    OldExercise("Dumbbell Chest Fly", "Chest Pec"),
//    OldExercise("Incline Cable Fly", "Chest Pec"),
//    OldExercise("Decline Cable Fly", "Chest Pec"),
//    OldExercise("Pull Up", "Back Lats"),
//    OldExercise("Chin Up", "Back Lats Bicep"),
//    OldExercise("Cable Chest Fly", "Chest Pec"),
//    OldExercise("Close-Grip Bench Press", "Tricep"),
//    OldExercise("Dumbbell Bench Press", "Chest Pec"),
//    OldExercise("Dumbbell Pullover", "Chest Pec"),
//    OldExercise("Larsen Press", "Chest Pec"),
//    OldExercise("Incline Dumbbell Press", "Chest Pec"),
//    OldExercise("Incline Push Up", "Chest Pec"),
//    OldExercise("Decline Push Up", "Chest Pec"),
//    OldExercise("Push Up", "Chest Pec"),
//    OldExercise("Machine Pec Fly", "Chest Pec"),
//    OldExercise("Machine Chest Press", "Chest Pec"),
//    OldExercise("Smith Machine Bench Press", "Chest Pec"),
//    OldExercise("Incline Smith Bench Press", "Chest Pec"),
//    OldExercise("Front Raise", "Shoulder Delt"),
//    OldExercise("Rear Delt Row", "Shoulder Delt"),
//    OldExercise("Upright Row", "Shoulder Delt"),
//    OldExercise("Cable Lateral Raise", "Shoulder Delt"),
//    OldExercise("Lateral Raise", "Shoulder Delt"),
//    OldExercise("Dumbbell Shoulder Press", "Shoulder Delt"),
//    OldExercise("Face Pull", "Shoulder Delt"),
//    OldExercise("Machine Lateral Raise", "Shoulder Delt"),
//    OldExercise("Machine Shoulder Press", "Shoulder Delt"),
//    OldExercise("Reverse Cable Fly", "Shoulder Delt"),
//    OldExercise("Reverse Dumbbell Fly", "Shoulder Delt"),
//    OldExercise("Reverse Machine Fly", "Shoulder Delt Back"),
//    OldExercise("Rear Delt Machine Fly", "Shoulder Delt Back"),
//    OldExercise("Squat Jerk", "Legs Quads"),
//    OldExercise("Split Jerk", "Shoulder Delt"),
//    OldExercise("Barbell Curl", "Bicep"),
//    OldExercise("Preacher Curl", "Bicep"),
//    OldExercise("Cable Curl", "Bicep"),
//    OldExercise("Concentration Curl", "Bicep"),
//    OldExercise("Dumbbell Curl", "Bicep"),
//    OldExercise("Hammer Curl", "Bicep"),
//    OldExercise("Incline Dumbbell Curl", "Bicep"),
//    OldExercise("Machine Bicep Curl", "Bicep"),
//    OldExercise("Spider Curl", "Bicep"),
//    OldExercise("Skullcrusher", "Tricep"),
//    OldExercise("Close-Grip Push Up", "Tricep"),
//    OldExercise("Dumbbell Triceps Extension", "Tricep"),
//    OldExercise("Overhead Triceps Extension", "Tricep"),
//    OldExercise("Tricep Pushdown", "Tricep"),
//    OldExercise("Dumbbell Kickbacks", "Tricep"),
//    OldExercise("Hack Squat", "Legs Quads"),
//    OldExercise("Barbell Lunge", "Legs Quads Glutes"),
//    OldExercise("Walking Lunge", "Legs Quads Glutes"),
//    OldExercise("Box Squat", "Legs Quads Glutes"),
//    OldExercise("Bulgarian Split Squat", "Legs Quads Glutes"),
//    OldExercise("Dumbbell Lunge", "Legs Quads Glutes"),
//    OldExercise("Front Squat", "Legs Quads Glutes"),
//    OldExercise("Arnold Press", "Shoulder Delt"),
//    OldExercise("Goblet Squat", "Legs Quads Glutes"),
//    OldExercise("Hip Adduction Machine", "Legs Glutes"),
//    OldExercise("Hip Abduction Machine", "Legs Glutes"),
//    OldExercise("Landmine Squat", "Legs Quads Glutes"),
//    OldExercise("Leg Extension", "Legs Quads"),
//    OldExercise("Leg Press", "Legs Quads Glutes"),
//    OldExercise("Lying Leg Curl", "Legs Hamstrings"),
//    OldExercise("Leg Curl", "Legs Hamstrings"),
//    OldExercise("Romanian Deadlift", "Legs Hamstrings"),
//    OldExercise("Side Lunge", "Legs Quads Glutes"),
//    OldExercise("Smith Machine Squat", "Legs Quads Glutes"),
//    OldExercise("Step Up", "Legs Quads Glutes"),
//    OldExercise("Back Extension", "Back"),
//    OldExercise("Barbell Shrug", "Back Traps"),
//    OldExercise("Cable Row", "Back Lats"),
//    OldExercise("Clean", "Legs Quads Glutes Shoulder Delt"),
//    OldExercise("Clean and Jerk", "Legs Quads Glutes Shoulder Delt"),
//    OldExercise("Dumbbell Row", "Back Lats"),
//    OldExercise("Dumbbell Shrug", "Back Traps"),
//    OldExercise("Good Morning", "Back Hamstrings"),
//    OldExercise("Hang Clean", "Legs Quads Glutes Shoulder Delt"),
//    OldExercise("Hang Snatch", "Legs Quads Glutes Shoulder Delt"),
//    OldExercise("Inverted Row", "Back Lats"),
//    OldExercise("Jefferson Curl", "Back Hamstrings"),
//    OldExercise("Lat Pulldown", "Back Lats"),
//    OldExercise("One-Handed Cable Row", "Back Lats"),
//    OldExercise("One-Handed Lat Pulldown", "Back Lats"),
//    OldExercise("Pendlay Row", "Back Lats"),
//    OldExercise("Power Clean", "Legs Quads Glutes Shoulder Delt"),
//    OldExercise("Power Snatch", "Legs Quads Glutes Shoulder Delt"),
//    OldExercise("Rack Pull", "Back Hamstrings"),
//    OldExercise("Seal Row", "Back Lats"),
//    OldExercise("Seated Machine Row", "Back Lats"),
//    OldExercise("Snatch", "Legs Quads Glutes Shoulder Delt"),
//    OldExercise("Stiff Leg Deadlift", "Back Hamstrings"),
//    OldExercise("T-Bar Row", "Back Lats"),
//    OldExercise("Trap Bar Deadlift", "Legs Back Hamstrings"),
//    OldExercise("Glute Bridge", "Legs Glutes"),
//    OldExercise("Hip Thrust", "Legs Hamstrings Glutes"),
//    OldExercise("Hip Thrust Machine", "Legs Hamstrings Glutes"),
//    OldExercise("Machine Glute Kickback", "Legs Glutes"),
//    OldExercise("One-Legged Hip Thrust", "Legs Hamstrings Glutes"),
//    OldExercise("One-Legged Leg Press", "Legs Quads Glutes"),
//    OldExercise("Cable Crunch", "Abs"),
//    OldExercise("Sit Up", "Abs"),
//    OldExercise("Lying Leg Raise", "Abs"),
//    OldExercise("Machine Crunch", "Abs"),
//    OldExercise("Ab Twist Machine", "Abs"),
//    OldExercise("Seated Calf Raise", "Legs Calves"),
//    OldExercise("Standing Calf Raise", "Legs Calves"),
//    OldExercise("Donkey Calf Raise", "Legs Calves"),
//    OldExercise("Wrist Curl", "Forearms"),
//    OldExercise("Wide-Grip Pull Up", "Back Lats"),
//    OldExercise("Wide-Grip Machine Row", "Back Lats"),
//    OldExercise("Wide-Grip Lat Pulldown", "Back Lats"),
//    OldExercise("Wide-Grip Cable Row", "Back Lats"),
//)